[build]
builder = "NIXPACKS"
buildCommand = "dotnet publish -c Release -o ./publish"

[deploy]
startCommand = "dotnet ./publish/CarCareTracker.dll"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10



